### ISSUE TITLE
Quick question...

### ISSUE THREAD

**Issue by eshapard** [He4eT/ifplayer#3]
Hey there, do the SAVE and RESTORE options in games actually create/read a file from the filesystem (and if so, where)? Thanks!

**Comment by He4eT** [comment]
Hello! Web applications do not have direct access to your file system.

All saved files are stored in the browser's localStorage.
You can use the browser's devtools to inspect the records.

Here you can see the code used for file operations:
https://github.com/He4eT/ifplayer/blob/master/src/components/Player/Player.jsx#L48

**Comment by eshapard** [comment]
Ah... good to know. Thanks!
