### ISSUE TITLE
Install/config instructions?

### ISSUE THREAD

**Issue by PriamX** [He4eT/ifplayer#6]
I'm a n00b to elseifplayer, just found it. Are there any installation and configuration instructions for this?

I've dropped it on my nginx server, but when going to elseifplayer/index.html it just says "loading" and never gets past that. I'm assuming here that I'm missing a big part of the picture.

Thanks!

**Comment by ttypelabs** [comment]
Same issue. So far I've tried:

`git clone https://github.com/He4eT/elseifplayer.git`
`cd elseifplayer`
`npm install`
`npm run-script build --public-url https://ifarchive.org/if-
archive/games/zcode/LostPig.z8`

Still getting the "loading" index.

**Comment by He4eT** [comment]
First of all, I apologise for the long silence.

@PriamX I've updated the `README.md`, it now has some basic instructions on how to set up the project initially. You need to build the project before uploading it to the server. According to you message you need to run `npm i`, then `npm run build /elseifplayer`, then copy files from appeared `docs` directory to you `elseifplayer` directory on the server.

@ttypelabs Unfortunately, you cannot specify "default" game without changing the source code. But you can build project with correct `public-url`, place files on your server and then provide direct link. It's possible to set up some redirect on your server. Something like `/gameName` -> `/elseifplayer/#/play/storyfile`

Feel free to ask if you need some additional help!
